'''
    A120 Find the Difference
    Two strings 's' and 't' are given.
    String 't' is generated by random shuffling string 's' and then add one more letter at a random position.
    Return the letter that was added to 't'.
    https://leetcode.com/problems/find-the-difference/
'''

s = input()
t = input()

for ch in t :
    if ch not in s :
        print(ch)